# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

variables:
  DOTNET_VERSION: "6.0" # Adjust to your required .NET Core version
  AZURE_WEBAPP_NAME: "hackmt-blazorwebapp" # Replace with your Azure Web App name
  APP_PATH: "$CI_PROJECT_DIR/"
  API_TOKEN: $DEPLOYMENT_TOKEN
  OUTPUT_PATH: 'publish'

cache:
  paths:
    - .nuget/packages

before_script:
  - apt-get update -qq && apt-get install -y unzip
  - dotnet --version
  - dotnet restore

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:$DOTNET_VERSION
  script:
    - dotnet publish -c Release -o $OUTPUT_PATH
  artifacts:
    paths:
      - $OUTPUT_PATH
    expire_in: 1 week

deploy:
  stage: deploy
  image: registry.gitlab.com/static-web-apps/azure-static-web-apps-deploy
  environment:
    name: production
    url: https://kind-desert-0c03e570f.4.azurestaticapps.net/
  only:
    - master # Adjust branch if needed
  script:
    - echo "Deploying to Azure App Service..."
  dependencies:
    - build
