stages:
  - build
  - deploy

variables:
  DOTNET_VERSION: "6.0" # Update to your Blazor Server app's .NET version
  AZURE_APP_NAME: "hackmt-blazorwebapp" # Replace with your Azure Web App name
  AZURE_REGION: "Central US" # Replace with your Azure region

before_script:
  - apt-get update -qq && apt-get install -y unzip
  - dotnet --version
  - dotnet restore

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:$DOTNET_VERSION
  script:
    # Restore dependencies and build the Blazor Server app
    - dotnet restore
    - dotnet publish -c Release -o publish
  artifacts:
    paths:
      - publish/

deploy:
  stage: deploy
  image: mcr.microsoft.com/azure-cli:latest
  script:
    # Authenticate with Azure using a Service Principal
    - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
    # Deploy the Blazor Server app to Azure Web App
    - az webapp up --name $AZURE_APP_NAME --resource-group $AZURE_RESOURCE_GROUP --plan $AZURE_APP_NAME-Plan --location $AZURE_REGION --sku F1 --runtime "DOTNET|6.0" --src-path publish/
