stages:
  - build
  - deploy

variables:
  DOTNET_VERSION: "6.0" # Update to your Blazor Server app's .NET version
  AZURE_APP_NAME: "hackmt-blazorwebapp" # Replace with your Azure Web App name
  AZURE_REGION: "Central US" # Replace with your Azure region

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:$DOTNET_VERSION
  before_script:
  - apt-get update -qq && apt-get install -y unzip zip
  - dotnet --version
  - dotnet restore
  script:
    # Restore dependencies and build the Blazor Server app
    - dotnet restore
    - dotnet publish -c Release -o publish
    - zip -r publish.zip publish/
  artifacts:
    paths:
      - publish.zip

deploy:
  stage: deploy
  image: mcr.microsoft.com/azure-cli:latest
  script:
    # Authenticate with Azure using a Service Principal
    - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
    # Deploy the Blazor Server app to Azure Web App
    - az webapp deploy --name $AZURE_APP_NAME --resource-group $AZURE_RESOURCE_GROUP --src-path publish.zip --type zip
