stages:
  - build
  - deploy

variables:
  BUILD_CONFIGURATION: "Release"
  DOTNET_VERSION: "6.0"
  AZURE_RESOURCE_GROUP: $CI_PROJECT_NAME # Replace with your resource group
  AZURE_APP_NAME: "your-app-name" # Replace with your App Service name

before_script:
  - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel $DOTNET_VERSION
  - apt-get update -qq && apt-get install -y unzip

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build --configuration $BUILD_CONFIGURATION
    - dotnet publish --configuration $BUILD_CONFIGURATION --output ./publish

deploy:
  stage: deploy
  image: ubuntu:latest
  before_script:
    - apt-get update && apt-get install -y ca-certificates curl apt-transport-https lsb-release gnupg
    - curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
    - install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
    - sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" > /etc/apt/sources.list.d/azure-cli.list'
    - apt-get update && apt-get install -y azure-cli
  script:
    - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
    - az webapp deployment source config-zip --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_APP_NAME --src ./publish.zip