stages:
  - build
  - deploy

variables:
  DOTNET_VERSION: "6.0" # Update to your Blazor Server app's .NET version
  AZURE_APP_NAME: "hackmt-blazorwebapp" # Replace with your Azure Web App name
  AZURE_REGION: "Central US" # Replace with your Azure region

before_script:
  # Install .NET Core SDK
  - apt-get update && apt-get install -y wget apt-transport-https
  - apt-get update && apt-get install -y dotnet-sdk-$DOTNET_VERSION
  # Install Azure CLI
  - curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
  - install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
  - sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" > /etc/apt/sources.list.d/azure-cli.list'
  - apt-get update && apt-get install -y azure-cli

build:
  stage: build
  script:
    # Restore dependencies and build the Blazor Server app
    - dotnet restore
    - dotnet publish -c Release -o publish
  artifacts:
    paths:
      - publish/

deploy:
  stage: deploy
  script:
    # Authenticate with Azure using a Service Principal
    - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
    # Deploy the Blazor Server app to Azure Web App
    - az webapp up --name $AZURE_APP_NAME --resource-group $AZURE_RESOURCE_GROUP --plan $AZURE_APP_NAME-Plan --location $AZURE_REGION --sku F1 --runtime "DOTNET|6.0" --src-path publish/
