stages:
  - build
  - deploy

variables:
  DOTNET_VERSION: "6.0" # Update to your Blazor Server app's .NET version
  AZURE_APP_NAME: "hackmt-blazorwebapp" # Replace with your Azure Web App name
  AZURE_REGION: "Central US" # Replace with your Azure region

before_script:
  # Install .NET Core SDK
  - apt-get update && apt-get install -y wget apt-transport-https
  - if [ -f /etc/os-release ]; then UBUNTU_VERSION=$(grep 'VERSION_ID' /etc/os-release | cut -d '"' -f 2); fi
  - if [ -z "$UBUNTU_VERSION" ]; then UBUNTU_VERSION="20.04"; fi # Default to 20.04 if detection fails
  - wget https://packages.microsoft.com/config/ubuntu/$UBUNTU_VERSION/packages-microsoft-prod.deb
  - dpkg -i packages-microsoft-prod.deb
  - apt-get update && apt-get install -y dotnet-sdk-$DOTNET_VERSION
  # Install Azure CLI
  - curl -sL https://aka.ms/InstallAzureCli | bash -s -- --accept-terms

build:
  stage: build
  script:
    # Restore dependencies and build the Blazor Server app
    - dotnet restore
    - dotnet publish -c Release -o publish
  artifacts:
    paths:
      - publish/

deploy:
  stage: deploy
  script:
    # Authenticate with Azure using a Service Principal
    - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
    # Deploy the Blazor Server app to Azure Web App
    - az webapp up --name $AZURE_APP_NAME --resource-group $AZURE_RESOURCE_GROUP --plan $AZURE_APP_NAME-Plan --location $AZURE_REGION --sku F1 --runtime "DOTNET|6.0" --src-path publish/
